import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "@/app/globals.css";

import HeaderFooterWrapper from "@/components/header-footer-wrapper/header";
import { Toaster } from "@/components/ui/toaster";
import { DialogStoreProvider } from "@/provider/Avatar-Dialog-Provider/avatar-dialog-provider";
import { NotificationStoreProvider } from "@/provider/Notification-Provider/notification-provider";
import { QuaryClientProvider } from "@/provider/QueryProvider/QuaryClientProvider";
import { AuthStoreProvider } from "@/provider/Store-Provider/auth-provider";
import { ThemeProvider } from "@/provider/Theme-Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AuthStoreProvider>
          <DialogStoreProvider>
            <NotificationStoreProvider>
              <QuaryClientProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <HeaderFooterWrapper>{children}</HeaderFooterWrapper>
                </ThemeProvider>
                <Toaster />
              </QuaryClientProvider>
            </NotificationStoreProvider>
          </DialogStoreProvider>
        </AuthStoreProvider>
      </body>
    </html>
  );
}
