import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "@/app/globals.css";

import Header from "@/components/header";
import HeaderFooterWrapper from "@/components/header-footer-wrapper/header";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { QuaryClientProvider } from "@/provider/QueryProvider/QuaryClientProvider";
import { AuthStoreProvider } from "@/provider/Store-Provider/auth-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AuthStoreProvider>
          <QuaryClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <HeaderFooterWrapper>{children}</HeaderFooterWrapper>
            </ThemeProvider>
            <Toaster />
          </QuaryClientProvider>
        </AuthStoreProvider>
      </body>
    </html>
  );
}
