export const PathPJ = {
    tutorProfile: "/profile/tutor-profile/",
    studentProfile: "/profile/student-profile/",
    announcement: "/announcement",
    announcementPagination: "/announcement/",
    announcementDetail: "/announcement/detail/",
    announcementSettings: "/announcement-settings",
    tutors: "/tutors",
    user: "/user/",
    tutorsPagination: "/tutors/",
    notification: "/notification",
    login: "/log-in",
    signup: "/sign-up",
    baseURL: process.env.NEXT_PUBLIC_API_URL,
    clientBaseURL: process.env.NEXT_PUBLIC_CLIENT_API_URL,
    defaultAvatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUspugOXub65sbxVHOEaD-JEKC8NNWgkWhlg&s",
}